Node.js HTTP request monitoring
tradingstrategy-ai/frontend pull request #176
Opened 2022-08-29 13:56 UTC by miohtama

This adds hooks for server-side rendering monitoring.

- Uses [web-top-node](https://www.npmjs.com/package/@trading-strategy-ai/web-top-node) package
- Monitoring API key `TOP_WEB_API_KEY` must be set in the secrets file

2022-08-29 15:25 UTC, kenkunz requested changes
It looks like did a global search/replace of `s/server/serverPlain/g` which resulted in a bunch of uninitended changes.

There's a regression of the `deps/theme` submodule commit hash (should be `a44ff27eab` which is latest commit to `master` on the theme repo).

Did you mean to keep `scripts/polka.js` and `scripts/polka-vs-express.js` (since "polka does not work" per `server.js` comment)?

Is the plan to have the top-based server running by default? If so, update last line of `Dockerfile`.

2022-08-29 15:25 UTC, kenkunz commented on docs/docker.md
unintended search/replace? (also in line 86 and 163).

2022-08-29 15:25 UTC, kenkunz commented on docs/old-production.md
> +This will run serverPlain-side generated (SSR) pages using node.js serverPlain.
same search/replace issue (also line 7)

2022-08-29 15:25 UTC, kenkunz commented on docs/staging.md
> +This will run serverPlain-side generated (SSR) pages using node.js serverPlain.
same search/replace issue (also lines 11, 13, 16, 29(

2022-08-29 15:25 UTC, kenkunz commented on docs/theme.md
> +dev serverPlain for the theme:
same search/replace issue

2022-08-29 15:25 UTC, kenkunz commented on scripts/server-plain.js
> +});
FYI, this file will go away after the SvelteKit upgrades are merged (invalid encoding bug has been fixed).

2022-08-29 15:25 UTC, kenkunz commented on src/routes/about/_Audience.svelte
> +				<Button label="Join our Discord serverPlain" icon="discord" href="https://discord.gg/en8tW6MDtw" target="_blank" />
same search/replace issue!

2022-08-29 15:25 UTC, kenkunz commented on src/routes/about/index.svelte
> +			<li><strong>Host private strategies</strong> on your own private serverPlain(s)</li>
same search/replace issue (also line 60)

2022-08-29 15:25 UTC, kenkunz commented on src/routes/slow-load.svelte
> +			because it doesn't do much serverPlain side. Page 2 (and beyond) will have a longer delay of {(page + 1) * 2} seconds.
same search/replace issue.

2022-08-29 15:25 UTC, kenkunz commented on src/routes/about/_Platform.svelte
> +			which is running off-chain and utilises high serverPlain capacity and provessing power not available on “pure” smart
same search/replace issue.

2022-08-30 07:12 UTC, miohtama commented on .env
> +# config.ts and available serverPlain-side or client-side (see hooks/index.ts).
Looks like TypeScript "refactor" was in fact "search and replace" under the hood

2022-08-31 20:56 UTC, kenkunz approved these changes
lgtm!

One small question – I noticed the default `Dockerfile` command is the (old) [`scripts/server-plain.js`](https://github.com/tradingstrategy-ai/frontend/blob/16e9f0d13b11bdf9f51160f7499557caa401b603/Dockerfile#L47), while the `docker-compose.yml` command is the (new) [`scripts/server.js`](https://github.com/tradingstrategy-ai/frontend/blob/16e9f0d13b11bdf9f51160f7499557caa401b603/docker-compose.yml#L15). Is that by design?

2022-09-01 12:57 UTC, merged